# Generated by Django 4.2.5 on 2023-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_item_brand_alter_item_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_cloth',
            field=models.CharField(default='rr', max_length=30, verbose_name='Тканина'),
            preserve_default=False,
        ),
    ]
