# Generated by Django 4.2.5 on 2023-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_item_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='sfdf', max_length=255, verbose_name='Опис'),
            preserve_default=False,
        ),
    ]
