# Generated by Django 4.2.5 on 2023-09-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_size',
        ),
    ]
