# Generated by Django 4.2.5 on 2023-09-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_item_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.size'),
            preserve_default=False,
        ),
    ]
