# Generated by Django 4.2.5 on 2023-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_item_item_state_alter_seasonality_seasonality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_text',
            field=models.CharField(default='', max_length=100, verbose_name='Опис'),
        ),
    ]
