# Generated by Django 4.2.5 on 2023-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_item_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_text',
            field=models.CharField(max_length=100, verbose_name='Опис'),
        ),
    ]
