# Generated by Django 4.2.5 on 2023-10-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_item_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.IntegerField(verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=2, verbose_name='Тип'),
        ),
    ]
