# Generated by Django 4.2.5 on 2023-10-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonality', models.IntegerField(verbose_name='Сезонність')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='Розмір')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name='Стан')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=30, verbose_name='Тип')),
                ('item_color', models.CharField(max_length=30, verbose_name='Колір')),
                ('item_brand', models.CharField(max_length=30, verbose_name='Бренд')),
                ('item_cloth', models.CharField(max_length=30, verbose_name='Тканина')),
                ('item_text', models.CharField(max_length=100, verbose_name='Опис')),
                ('item_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.size')),
                ('item_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.state')),
            ],
        ),
    ]
