# Generated by Django 4.2.5 on 2023-10-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.size', verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.state', verbose_name='Стан'),
        ),
    ]
