# Generated by Django 4.2.5 on 2023-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_brand',
            field=models.CharField(default=None, max_length=30, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.CharField(max_length=30, verbose_name='Колір'),
        ),
    ]
