# Generated by Django 4.2.5 on 2023-10-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_item_size_alter_item_item_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Тип')),
                ('surname', models.CharField(max_length=30, verbose_name='Тип')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Тип')),
                ('city', models.CharField(max_length=30, verbose_name='Тип')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Тип')),
                ('email', models.CharField(max_length=30, verbose_name='Тип')),
                ('passport_code', models.CharField(max_length=30, verbose_name='Тип')),
                ('date_of_birth', models.CharField(max_length=30, verbose_name='Тип')),
                ('password', models.CharField(max_length=30, verbose_name='Тип')),
                ('credit_cars', models.CharField(max_length=30, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id_fabric', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_name', models.CharField(max_length=30, verbose_name='Назва тканини')),
                ('destiny', models.CharField(max_length=30, verbose_name='Щільність')),
                ('elasticity', models.CharField(max_length=30, verbose_name='Еластичність')),
                ('breathability', models.CharField(max_length=30, verbose_name='Повітропроникність')),
                ('surface_texture', models.CharField(max_length=30, verbose_name='Повітропроникність')),
                ('compression_resistance', models.CharField(max_length=30, verbose_name='Стійкість до стиснення')),
                ('color_fastness', models.CharField(max_length=30, verbose_name='Стійкість кольору')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.CharField(max_length=30, verbose_name='Тип')),
                ('the_total_cost', models.CharField(max_length=30, verbose_name='Тип')),
                ('method_of_delivery', models.CharField(max_length=30, verbose_name='Тип')),
                ('payment_type', models.CharField(max_length=30, verbose_name='Тип')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30, verbose_name='Назва компанії')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Контактна персона')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(max_length=30, verbose_name='Адреса')),
                ('email', models.CharField(max_length=30, verbose_name='Пошта')),
            ],
        ),
        migrations.DeleteModel(
            name='Seasonality',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='id_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_cloth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_state',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
        migrations.AddField(
            model_name='item',
            name='chemical_treatment',
            field=models.CharField(default='nice', max_length=30, verbose_name='Хімічна обробка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_appearance',
            field=models.DateTimeField(default='2000-02-10 15:45:46', verbose_name='Дата появи товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='nice', max_length=30, verbose_name='Ціна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='seasonality',
            field=models.CharField(default='nice', max_length=30, verbose_name='Сезонність'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='nice', max_length=5, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(default='nice', max_length=30, verbose_name='Стан'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fabric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.receipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier'),
            preserve_default=False,
        ),
    ]
