# Generated by Django 4.2.5 on 2023-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_customer_fabric_receipt_supplier_delete_seasonality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='destiny',
            field=models.CharField(choices=[('Помірна', 'default'), ('Висока', 'default1'), ('Груба', 'default2'), ('Середня', 'default3'), ('Різна', 'default4'), ('Низька', 'default5')], default='Помірна', max_length=30, verbose_name='Щільність'),
        ),
    ]
