# Generated by Django 4.2.5 on 2023-10-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_fabric_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_cars',
            field=models.CharField(max_length=16, verbose_name='Номер кредитної карти'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=30, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_code',
            field=models.CharField(max_length=10, verbose_name='Код паспорту'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=40, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='elasticity',
            field=models.CharField(choices=[('Помірна', 'default'), ('Висока', 'default1'), ('Груба', 'default2'), ('Середня', 'default3'), ('Різна', 'default4'), ('Низька', 'default5')], default='Помірна', max_length=30, verbose_name='Еластичність'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_of_purchase',
            field=models.DateTimeField(verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='the_total_cost',
            field=models.FloatField(verbose_name='Загальна вартість'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
