# Generated by Django 4.2.5 on 2023-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='4d', max_length=30, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Опис'),
        ),
    ]
