# Generated by Django 4.2.5 on 2023-09-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_item_type_alter_item_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='item_text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_type',
        ),
    ]
