# Generated by Django 4.2.5 on 2023-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_text_item_item_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=5, verbose_name='Розмір'),
        ),
    ]
