# Generated by Django 4.2.5 on 2023-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_item_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='receipt',
        ),
        migrations.AddField(
            model_name='item',
            name='sold_or_not',
            field=models.BooleanField(default=False, verbose_name='Куплена?'),
        ),
    ]
