# Generated by Django 4.2.5 on 2023-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_item_receipt_item_sold_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=5, verbose_name='Розмір'),
        ),
    ]
