# Generated by Django 4.2.5 on 2023-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_fabric_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='destiny',
            field=models.CharField(choices=[('high', 'Висока'), ('moderate', 'Помірна'), ('average', 'Середня'), ('low', 'Низька'), ('different', 'Різна')], max_length=30, verbose_name='Щільність'),
        ),
    ]
