# Generated by Django 4.2.5 on 2023-10-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_queryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='color_fastness',
            field=models.CharField(choices=[('high fastness', 'Висока стійкість'), ('medium fastness', 'Середня стійкість'), ('low fastness', 'Низька стійкість'), ('unknown', 'Невідомо')], max_length=30, verbose_name='Стійкість кольору'),
        ),
    ]
