# Generated by Django 4.2.5 on 2023-10-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_fabric_color_fastness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='chemical_treatment',
            field=models.CharField(choices=[('not processed', 'Не оброблено'), ('needs chemical treatment', 'Потребує хімічної обробки'), ('treated with light chemistry', 'Оброблено легкою хімією'), ('treated with heavy chemicals', 'Оброблено важкою хімією'), ('treated with anti-allergic agents', 'Оброблено протиалергічними засобами')], max_length=300, verbose_name='Хімічна обробка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('beige', 'Бежевий'), ('white', 'Білий'), ('blue', 'Блакитний'), ('burgundy', 'Бордовий'), ('yellow', 'Жовтий'), ('green', 'Зелений'), ('brown', 'Коричневий'), ('orange', 'Оранжевий'), ('pink', 'Рожевий'), ('blue', 'Синій'), ('gray', 'Сірий'), ('red', 'Червоний'), ('black', 'Чорний'), ('purple', 'Фіолетовий'), ('other color', 'Інші кольори'), ('multicolored', 'Різнокольоровий'), ('print', 'Принт')], max_length=30, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seasonality',
            field=models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Літо'), ('autumn', 'Осінь'), ('demi-season', 'Демісезон'), ('all', 'Любий')], max_length=300, verbose_name='Сезонність'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XXL'), ('xxl', 'XXL')], max_length=30, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Стан'),
        ),
    ]
