# Generated by Django 4.2.5 on 2023-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_item_chemical_treatment_alter_item_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='chemical_treatment',
            field=models.CharField(choices=[('not processed', 'Не оброблено'), ('needs chemical treatment', 'Потребує хімічної обробки'), ('treated with light chemistry', 'Оброблено легкою хімією'), ('treated with heavy chemicals', 'Оброблено важкою хімією'), ('treated with anti-allergic agents', 'Оброблено протиалергічними засобами')], max_length=100, verbose_name='Хімічна обробка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seasonality',
            field=models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Літо'), ('autumn', 'Осінь'), ('demi-season', 'Демісезон'), ('all', 'Любий')], max_length=100, verbose_name='Сезонність'),
        ),
    ]
