# Generated by Django 4.2.5 on 2023-10-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_item_chemical_treatment_alter_item_seasonality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Тканина', to='catalog.fabric'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Постачальник', to='catalog.supplier'),
        ),
    ]
