# Generated by Django 4.2.5 on 2023-10-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_item_fabric_alter_item_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='catalog.item'),
        ),
    ]
