# Generated by Django 4.2.5 on 2023-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_receipt_id_customer_alter_receipt_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_or_not',
            field=models.CharField(choices=[('true', 'Так'), ('false', 'Ні')], default=False, max_length=10, verbose_name='Наявність'),
        ),
    ]
