# Generated by Django 4.2.5 on 2023-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_item_sold_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('female', 'Так'), ('male', 'Так'), ('unisex', 'Так')], default='unisex', max_length=30, verbose_name='Приналежність'),
            preserve_default=False,
        ),
    ]
