# Generated by Django 4.2.5 on 2023-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('female', 'Жіночій'), ('male', 'Чоловічий'), ('unisex', 'Унісекс')], max_length=30, verbose_name='Приналежність'),
        ),
    ]
