# Generated by Django 4.2.5 on 2023-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('beige', 'Бежевий'), ('white', 'Білий'), ('blue', 'Блакитний'), ('burgundy', 'Бордовий'), ('yellow', 'Жовтий'), ('green', 'Зелений'), ('brown', 'Коричневий'), ('orange', 'Помаранчевий'), ('pink', 'Рожевий'), ('blue', 'Синій'), ('gray', 'Сірий'), ('red', 'Червоний'), ('black', 'Чорний'), ('purple', 'Фіолетовий'), ('other color', 'Інші кольори'), ('multicolored', 'Різнокольоровий'), ('print', 'Принт')], max_length=30, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(db_comment='Опишіть невеликим текстом річ', max_length=100, verbose_name='Стан'),
        ),
    ]
