# Generated by Django 4.2.5 on 2023-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_rename_address_supplier_city_alter_item_fabric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Місто'),
        ),
    ]
