# Generated by Django 4.2.5 on 2023-10-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_supplier_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fabric',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fabric', verbose_name='Тканина'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier', verbose_name='Постачальник'),
        ),
    ]
