# Generated by Django 4.2.5 on 2023-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_rename_contact_person_supplier_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='blabla', max_length=30, verbose_name='Вулиця'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_house',
            field=models.CharField(default='4', max_length=30, verbose_name='Номер будинку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person_surname',
            field=models.CharField(default='bla', max_length=50, verbose_name='Прізвище контактної персони'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я контактної персони"),
        ),
    ]
