# Generated by Django 4.2.5 on 2023-11-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_customer_address_customer_number_of_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='supplier',
            new_name='id_supplier',
        ),
    ]
