# Generated by Django 4.2.5 on 2023-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_rename_id_supplier_item_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold_or_not',
        ),
    ]
