# Generated by Django 4.2.5 on 2023-11-18 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_remove_item_sold_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Номер телефона повинен бути у форматі: '+380123456789'.", regex='^\\+380\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
