# Generated by Django 4.2.5 on 2023-11-18 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='fabric_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Назва тканини'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_appearance',
            field=models.DateField(verbose_name='Дата появи товару'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name="Ім'я контактної персони"),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Прізвище контактної персони'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Номер телефона повинен бути у форматі: '+380123456789'.", regex='^\\+380\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
