# Generated by Django 4.2.5 on 2023-11-18 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_alter_fabric_fabric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('significant defects', 'Є значні дефекти'), ('minor defects', 'Є незначні дефекти'), ('slightly worn', 'Трішки ношений'), ('new', 'Новий')], max_length=100, verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Номер телефона повинен бути у форматі: '+380 12-345-67-89'.", regex='^\\+380 \\d{2}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
