# Generated by Django 4.2.5 on 2023-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='breathability',
            field=models.CharField(choices=[('Низька', 'Низька'), ('Майже відсутня', 'Майже відсутня'), ('Середня', 'Середня'), ('Висока', 'Висока')], max_length=30, verbose_name='Повітропроникність'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='color_fastness',
            field=models.CharField(choices=[('Висока стійкість', 'Висока стійкість'), ('Середня стійкість', 'Середня стійкість'), ('Низька стійкість', 'Низька стійкість'), ('Невідомо', 'Невідомо')], max_length=30, verbose_name='Стійкість кольору'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='compression_resistance',
            field=models.CharField(choices=[('Висока стійкість', 'Висока стійкість'), ('Середня стійкість', 'Середня стійкість'), ('Низька стійкість', 'Низька стійкість'), ('Антикомпресійна тканина', 'Антикомпресійна тканина')], max_length=30, verbose_name='Стійкість до стиснення'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='destiny',
            field=models.CharField(choices=[('Висока', 'Висока'), ('Помірна', 'Помірна'), ('Середня', 'Середня'), ('Низька', 'Низька'), ('Різна', 'Різна')], max_length=30, verbose_name='Щільність'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='elasticity',
            field=models.CharField(choices=[('Не еластична', 'Не еластична'), ('Майже не еластична', 'Майже не еластична'), ('Частково еластична', 'Частково еластична'), ('Добре еластична', 'Добре еластична')], max_length=30, verbose_name='Еластичність'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='surface_texture',
            field=models.CharField(choices=[('Блискуча', 'Блискуча'), ('Гладка', 'Гладка'), ('Гофрована', 'Гофрована'), ('Діагональна', 'Діагональна'), ('Матова', 'Матова'), ("М'яка", "М'яка"), ('Рельєфна', 'Рельєфна'), ('Рубчаста', 'Рубчаста'), ('Сітчаста', 'Сітчаста'), ('Складна', 'Складна'), ('Смужкова', 'Смужкова'), ('Шорстка', 'Шорстка')], max_length=30, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='item',
            name='chemical_treatment',
            field=models.CharField(choices=[('Не оброблено', 'Не оброблено'), ('Потребує хімічної обробки', 'Потребує хімічної обробки'), ('Оброблено легкою хімією', 'Оброблено легкою хімією'), ('Оброблено важкою хімією', 'Оброблено важкою хімією'), ('Оброблено протиалергічними засобами', 'Оброблено протиалергічними засобами')], max_length=100, verbose_name='Хімічна обробка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Бежевий', 'Бежевий'), ('Білий', 'Білий'), ('Блакитний', 'Блакитний'), ('Бордовий', 'Бордовий'), ('Жовтий', 'Жовтий'), ('Зелений', 'Зелений'), ('Коричневий', 'Коричневий'), ('Помаранчевий', 'Помаранчевий'), ('Рожевий', 'Рожевий'), ('Синій', 'Синій'), ('Сірий', 'Сірий'), ('Червоний', 'Червоний'), ('Чорний', 'Чорний'), ('Фіолетовий', 'Фіолетовий'), ('Інші кольори', 'Інші кольори'), ('Різнокольоровий', 'Різнокольоровий'), ('Принт', 'Принт')], max_length=30, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Жіночій', 'Жіночій'), ('Чоловічий', 'Чоловічий'), ('Унісекс', 'Унісекс')], max_length=30, verbose_name='Приналежність'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seasonality',
            field=models.CharField(choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Літо', 'Літо'), ('Осінь', 'Осінь'), ('Демісезон', 'Демісезон'), ('Любий', 'Любий')], max_length=100, verbose_name='Сезонність'),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('Є значні дефекти', 'Є значні дефекти'), ('Є незначні дефекти', 'Є незначні дефекти'), ('Трішки ношений', 'Трішки ношений'), ('Новий', 'Новий')], max_length=100, verbose_name='Стан'),
        ),
    ]
