# Generated by Django 4.2.5 on 2023-11-22 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_alter_fabric_breathability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_of_house',
            field=models.IntegerField(verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Прізвище'),
        ),
    ]
