# Generated by Django 4.2.5 on 2023-11-22 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='customer_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_of_birth',
            new_name='customer_date_of_birth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='middle_name',
            new_name='customer_middle_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='number_of_house',
            new_name='customer_number_of_house',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='customer_password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='customer_surname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_cars',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_credit_card',
            field=models.IntegerField(default='1', unique=True, verbose_name='Номер кредитної карти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='bbbbb@bbb.com', max_length=100, unique=True, verbose_name='Пошта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_passport_code',
            field=models.CharField(default='1111111', max_length=10, unique=True, verbose_name='Код паспорту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone_number',
            field=models.CharField(default='+380 12-345-67-89', max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Номер телефона повинен бути у форматі: '+380 12-345-67-89'.", regex='^\\+380 \\d{2}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
