# Generated by Django 4.2.5 on 2023-11-22 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_customer_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_credit_card',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card', message='Номер картки записується у вигляді хххх хххх хххх хххх', regex='^\\d{4} \\d{4} \\d{4} \\d{4}$')], verbose_name='Номер кредитної карти'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_passport_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Номер паспорта не починається з 0', regex='^\\d{4} \\d{4} \\d{4} \\d{4}$')], verbose_name='Код паспорту'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Мінімум вісім символів, одна літера, одна цифра та один спеціальний символ', regex='^\\+380 \\d{2}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Пароль'),
        ),
    ]
