# Generated by Django 4.2.5 on 2023-11-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_alter_receipt_id_customer_alter_receipt_id_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item', unique=True, verbose_name='Товар'),
        ),
    ]
