# Generated by Django 4.2.5 on 2023-11-22 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_alter_receipt_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_passport_code',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Номер паспорта не починається з 0', regex='^[1-9]\\d{9}$')], verbose_name='Код паспорту'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Мінімум вісім символів, одна літера, одна цифра та один спеціальний символ: @ $ ! % * # ? & +', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&+])[A-Za-z\\d@$!%*#?&+]{8,}$')], verbose_name='Пароль'),
        ),
    ]
