# Generated by Django 4.2.5 on 2023-11-22 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_alter_customer_customer_passport_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Вулиця'),
        ),
    ]
