# Generated by Django 4.2.5 on 2023-11-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_alter_customer_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='number_of_receipt',
            field=models.IntegerField(default='55555555', verbose_name='Номер чеку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Використовуйте українську мову.', regex="^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\\'\\s]+$")], verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_passport_code',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Номер паспорта не починається з 0 та містить 10 символів', regex='^[1-9]\\d{9}$')], verbose_name='Код паспорту'),
        ),
    ]
