# Generated by Django 4.2.5 on 2023-11-24 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_receipt_number_of_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_passport_code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Номер паспорта не починається з 0 та містить 10 символів', regex='^[1-9]\\d{9}$')], verbose_name='Код паспорту'),
        ),
    ]
