# Generated by Django 4.2.5 on 2023-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_receipt_the_item_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='the_total_cost',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='the_item_cost',
            field=models.IntegerField(verbose_name='Вартість товару'),
        ),
    ]
