# Generated by Django 4.2.5 on 2023-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_remove_receipt_the_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='the_item_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вартість товару'),
        ),
    ]
