# Generated by Django 4.2.5 on 2023-11-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_alter_receipt_number_of_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_of_appearance',
        ),
    ]
