# Generated by Django 4.2.5 on 2023-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_alter_receipt_number_of_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number_of_receipt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер чеку'),
        ),
    ]
