# Generated by Django 4.2.5 on 2023-12-26 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number_of_house',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_number', message='Введіть число від 1 до 500.', regex='^(500|[1-4]?[0-9]{1,2})$')], verbose_name='Номер будинку'),
        ),
    ]
