# Generated by Django 4.2.5 on 2023-12-27 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_alter_customer_customer_number_of_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Від 8 символів, латинська літера, цифра та спеціальний символ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$!%*#?&+])[A-Za-z\\d@$!%*#?&+]{8,}$')], verbose_name='Пароль'),
        ),
    ]
